name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build with PyInstaller
      run: pyinstaller --clean SyncNon-SteamGames.spec

    - name: Read Changelog
      id: changelog
      run: |
        $VERSION = $env:GITHUB_REF_NAME
        $content = Get-Content CHANGELOG.md
        $start = $false
        $bodyLines = @()
        foreach ($line in $content) {
            if ($line -match "## \[$VERSION\]") {
                $start = $true
                continue
            }
            if ($start -and $line -match "^## \[") {
                break
            }
            if ($start) {
                $bodyLines += $line
            }
        }
        $BODY = $bodyLines -join "`n"
        "content<<EOF" | Out-File -FilePath $env:GITHUB_OUTPUT -Append -Encoding utf8
        $BODY | Out-File -FilePath $env:GITHUB_OUTPUT -Append -Encoding utf8
        "EOF" | Out-File -FilePath $env:GITHUB_OUTPUT -Append -Encoding utf8

    - name: Create Release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: Release ${{ github.ref_name }}
        tag_name: ${{ github.ref_name }}
        body: |
          ${{ steps.changelog.outputs.content }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/SyncNon-SteamGames.exe
        asset_name: SyncNon-SteamGames.exe
        asset_content_type: application/octet-stream
